name: docker image for Grafana (amd64)

on:
  pull_request:
    paths:
      - Dockerfile*
      - .github/workflows/push-docker-amd64.yaml
      - .github/workflows/push-docker-image.yaml
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  amd64:
    uses: ./.github/workflows/push-docker-image.yaml
    secrets: inherit
    with:
      quay_repository: "quay.io/tigrisdata/grafana"
      file: Dockerfile
      platforms: amd64
      event_name: ${{ github.event_name }}
